#################################### Server ####################################
[server]
# Protocol (http, https, h2, socket)
protocol = https

# The http port to use
http_port = 3000

# https certs & key file
cert_file = C:/Program Files/GrafanaLabs/grafana/conf/server.crt
cert_key = C:/Program Files/GrafanaLabs/grafana/conf/server.key